### PR TITLE
added created/last_modified values and removed navigation_id from populate

### PR DESCRIPTION
**Pull request by SysPete**
thanks for bin/populate - found a few problems when using it in my Pg environment

### CODE REVIEW

**Comment by racke** [comment]
Which version of Interchange6::Schema did you use? WIth 0.012 it should do the right thing with created/last_modified in addresses.

The patch for the navigation_id makes sense for me.

Regards
             Racke

**Comment by SysPete** [comment]
I6:Schema is 0.012 - I'm using master which I have at 5b4007ad670228ab19a0aab1ab6769be469ebde7

I've re-read the POD for DBIx::Class::ResultSet and it seems that the problem is due to calling populate in void context which bypasses new/insert calls and so D::C::TimeStamp extension is not triggered. If the calls are non-void then populate should do things as expected.

I'll cleanup and resubmit the patch with simple scalar assignments.

**Comment by racke** [comment]
On 01/21/2014 12:44 PM, SysPete wrote:

> I6:Schema is 0.012 - I'm using master which I have at 5b4007ad670228ab19a0aab1ab6769be469ebde7
> 
> I've re-read the POD for DBIx::Class::ResultSet and it seems that the problem is due to calling populate in void context which bypasses new/insert calls and so D::C::TimeStamp extension is not triggered. If the calls are non-void then populate should do things as expected.
> 
> I'll cleanup and resubmit the patch with simple scalar assignments.

Ah, right - yeah using populate isn't a good idea :-). I think we are better off with resultset('Address')->create(...) etc.
Thanks for your assistance!

Regards
    Racke

## 

Perl and Dancer Development

Visit our Open Source conference on E-commerce:

http://www.ecommerce-innovation.com/

**Comment by SysPete** [comment]
simply doing:

my $foo = schema->populate(..

causes create to be called for each item and saves lots of typing compared to many creates. Also when using populate with fk data in void context forces create instead of the fast bypass method.

I'll delete this pull request for now and let you decide which way to go.

R.
PeteM

**Pull request closed without merging**
